### ISSUE TITLE
Startup error on Megaman X2/3 - CX4?

### ISSUE THREAD

**Issue by juraisa** [agg23/openfpga-SNES#1]
Both games throw an error at startup, I assume it's CX4 related as X3 is missing the spotlight effects during the intro. Game continues to intro after the IMMEDIATE ROM - ERROR screen. I don't have the dock so I can't invoke the CX4 menu via secondary controller, only making an issue as CX4 was listed on the initial release of supported chips

**Comment by agg23** [comment]
Yep, I'm seeing this too. I apparently forgot to test it.

Thanks for the report. I'll look into it soon.
