### ISSUE TITLE
Pop'n TwinBee: Rainbow Bell Adventures not working.

### ISSUE THREAD

**Issue by ifighftdragons** [agg23/openfpga-SNES#16]
Pop'n TwinBee: Rainbow Bell Adventures not working.

Works flawlessly on original SNES via flashcart, Super Nt, and various emulators.

**Comment by ifighftdragons** [comment]
Got it working by fixing checksum and internal ROM size.

**Comment by ChrisitanNavas** [comment]
@ifighftdragons what Rom size did you change it to ?
