### ISSUE TITLE
Live a Live Eng Patch v2.0 translation loads to black screen

### ISSUE THREAD

**Issue by fourswordslink** [agg23/openfpga-SNES#20]
Game boots to either a black screen or a black screen with a line of pixels on top.

Using fresh rom from No-Intro (has no header) + Aeon Genesis 2.0 English translation patch, I receive the above issues.
This does not happen on a non-patched JPN rom, or using the older 1.0 translation patch. Also verified the 2.0 patched rom runs in BSNES/higan.
Original:
<img width="405" alt="original" src="https://user-images.githubusercontent.com/113801573/190875511-f2805fe2-fa8b-46c4-9384-628a6af65e1d.png">
Patched (with 2.0 translation):
<img width="409" alt="patched" src="https://user-images.githubusercontent.com/113801573/190875512-daa45e22-243b-4fc1-b0d5-6538d01ce1fc.png">

**Comment by agg23** [comment]
Try these instructions. It seems to have fixed several other patched ROMs with issues: https://github.com/agg23/openfpga-SNES/issues/3#issuecomment-1250088480

**Comment by fourswordslink** [comment]
> Try these instructions. It seems to have fixed several other patched ROMs with issues: [#3 (comment)](https://github.com/agg23/openfpga-SNES/issues/3#issuecomment-1250088480)

That worked for me. Thank you very much
