### ISSUE TITLE
Megaman X2 Overdrive Ostrich 

### ISSUE THREAD

**Issue by miavuli** [agg23/openfpga-SNES#23]
When fighting Overdrive Ostrich in Megaman X2 he will occasionally shoot a sonic slicer at you from his mouth. Normally this will move towards you but on this core it just hovers in mid air.

**Comment by SegaSnatcher** [comment]
Possibly another CX4 related issue since it was not properly implemented.

**Comment by miavuli** [comment]
https://user-images.githubusercontent.com/26606694/190905545-6da8930a-19b9-4379-925a-5a865d2c60ec.mp4

Here is a video of the issue

**Comment by miavuli** [comment]
I also found a another problem in this stage. When riding on the bike you're supposed to shoot a bridge with it but that bridge is completely missing. I have attached a video 

https://user-images.githubusercontent.com/26606694/190906587-efe21f4a-1ea9-4516-888a-cfd621d61301.mp4

**Comment by ifighftdragons** [comment]
CX4 issue. Good documentation. Please close this issue, and include this info in the other issue post. No need for two issues on the same game.

**Comment by miavuli** [comment]
Adding comments to other post
