### ISSUE TITLE
DSP Games Not loading?

### ISSUE THREAD

**Issue by DJBabyBuster** [agg23/openfpga-SNES#26]
Cannot get Super Mario Kart or Pilot Wings to boot on new update. After load status bar completes on either game, I'm just getting a blank black screen, no sound.  Other games using the SA-1 and Super FX games running great.

**Comment by agg23** [comment]
Have you confirmed that there are no headers present?

**Comment by DJBabyBuster** [comment]
That was indeed the issue, grabbed no headers and we're in business, thanks!
