### ISSUE TITLE
Half screen issue

### ISSUE THREAD

**Issue by miavuli** [agg23/openfpga-SNES#27]
After updating to the latest version I now have half a screen on every game.
![20220919_232225](https://user-images.githubusercontent.com/26606694/191160444-d72386ac-70fa-4763-9987-2463047117ee.jpg)

**Comment by agg23** [comment]
You didn't copy over all of the files. You need to copy over everything, including the `video.json`.

**Comment by miavuli** [comment]
I copied over all of the files. I just unzip the main file and drop all of the folders into the root. For some reason snes_main is not there. 
![Capture](https://user-images.githubusercontent.com/26606694/191161257-86b0f8bd-5777-4502-b6cd-61e85d865578.PNG)

**Comment by agg23** [comment]
I'm not sure what you're saying. The `snes_main.rev` file is present in the zip.

**Comment by miavuli** [comment]
I don't see it for some reason. I'm not sure why. When I download the zip I'm presented with these files only. 
![Capture](https://user-images.githubusercontent.com/26606694/191162243-14b01af7-0007-4e01-8e2f-bc3269f9abe8.PNG)

**Comment by agg23** [comment]
You aren't downloading the release, but the repo. You should be clicking on the "Release" button on the right hand side and downloading the `agg23.SNES_0.2.0_2022-09-19.zip` from https://github.com/agg23/openfpga-SNES/releases/tag/0.2.0

**Comment by miavuli** [comment]
Thank you! Thats what the issue was!
