### ISSUE TITLE
F1 Race of champions ST010

### ISSUE THREAD

**Issue by terminator2k2** [agg23/openfpga-SNES#28]
F1 Race of champions (ST010 chip)  glitches in game
![Screenshot 2022-09-20 08-31-22](https://user-images.githubusercontent.com/48845336/191195629-e877af83-aa24-4ee1-9188-2ea65f257219.png)

**Comment by SegaSnatcher** [comment]
Was this chip supported in the previous release?

**Comment by agg23** [comment]
It was not. Uses a DSP variant, but I've known about this game (thanks to @terminator2k2) and it hasn't been working for a while. I'm wondering if it has sensitive memory timing issues or something.
