### ISSUE TITLE
Final Fantasy 5 with English translation patch 1.10 doesn't load

### ISSUE THREAD

**Issue by mattd121** [agg23/openfpga-SNES#30]
Final Fantasy 5 with the English 1.10 translation patch doesn't load past the opening screen. During the opening sequence you can normally press the controller buttons to get to the load save/new game screen. However, as the opening screen fades out the music volume lowers but then stays playing as the screen goes to black and remains that way. You are unable to progress beyond this point. Japanese untranslated version loads fine.

**Comment by agg23** [comment]
See #3

**Comment by mattd121** [comment]
Thank you that worked.
