### ISSUE TITLE
Mega Man X high pitched sound

### ISSUE THREAD

**Issue by agg23** [agg23/openfpga-SNES#31]
Report from https://twitter.com/MrPixelSynth:

In Mega Man X on Launch Octopus stage. There is this really weird high pitched audio noise sometimes when X is under water

He ran through the entire game and didn't notice any other issues.

**Comment by miavuli** [comment]
Unless he is taking about the Utuboros serpent making a high pitch noise when you shoot it(completely normal) I can't reproduce this issue. 
![SmartSelect_20220921_173020_YouTube](https://user-images.githubusercontent.com/26606694/191614396-dd2347d1-f2e0-4500-bae4-2eceb758dacc.jpg)

**Comment by agg23** [comment]
Turns out this is part of the game, it's just easier to hear on the Pocket

https://twitter.com/MrPixelSynth/status/1573696456086757382
