### ISSUE TITLE
Super Smash T.V. (USA) Input Button Mapping Issue

### ISSUE THREAD

**Issue by xportz** [agg23/openfpga-SNES#35]
Pressing "Y" pauses the game and adds a 2nd player.  It's almost as if "Y" is also mapped to "START" on a 2nd controller.  But I'm only playing on the Pocket.  I also tested with "Use Multitap" on and off, with the same results.  I don't believe this issue existed in the previous build as I was successfully playing the game prior to updating to 0.3.0.

**Comment by agg23** [comment]
Fix incoming. Sorry about that
