### ISSUE TITLE
Castlevania - Dracula X crashing core

### ISSUE THREAD

**Issue by DJBabyBuster** [agg23/openfpga-SNES#38]
Trying to run Castlevania - Dracula X, I get a blank screen after load, the when trying to quit the core, it won't exit and I have to hard reboot the pocket

**Comment by ifighftdragons** [comment]
Dracula X works like a charm. 
You just need to use SNES Advanced ROM Utility to either fix Checksum, ROM Size and/or remove header.

**Comment by agg23** [comment]
> when trying to quit the core, it won't exit and I have to hard reboot the pocket

That's a pretty big deal. What firmware version are you running? It's stuck at a completely black screen? Do other games work?

**Comment by DJBabyBuster** [comment]
The latest 0.3.1
Yeah it's the first time I've encountered a rom that crashed the core like that. 
It exhibited the same behavior 3 times, but trying again just now it won't load and I'm getting "Error in Framework File ID [10] too large"

**Comment by agg23** [comment]
Deleting the save file for the game should fix that problem (but not the black screen)

**Comment by agg23** [comment]
Sorry for the delay. Is this still occurring? I cannot reproduce. Please reopen if you can reproduce
