### ISSUE TITLE
Soft lock going back too many times in Load SMC menu

### ISSUE THREAD

**Issue by treyturner** [agg23/openfpga-SNES#4]
Affects 0.1.0.

- Load core
- Load game
- Press Analogue button
- Core Settings -> Load SMC
- Press B, B, B to go back, back, back
- Console is now soft-locked with the menu flashing on and off
- Must hold down the power button to power off

It might be good if there was a way to exit the Load SMC menu without loading another game, ie. cancel that operation. As things stand you can hide the menu with the Analogue button, but you're still in the Load SMC menu when you press it again.

**Comment by mikey303** [comment]
I believe this is an AnalogueOS issue as I can replicate this with every other core. I've reported it to the AnalogueOS repository (https://github.com/frederic-mahe/Analogue-Pocket/issues/99)
