### ISSUE TITLE
Kyuuyaku Megami Tensei is Crashing possibly. 

### ISSUE THREAD

**Issue by The-grey-ghost** [agg23/openfpga-SNES#41]
When attempting to use the core it shows the Atlus logo but after attempting both letting it play and pressing any button to skip, it leads to a black screen where no audio plays, not even a hanging note.  Attempted to use both an English patched version and then unpatched version to same result, no saves or anything attempted to be brought over. The analogue button still works and allows me to quit out.

**Comment by agg23** [comment]
I cannot repro. I did not try the English patch, but the original Japanese ROM ran just fine

**Comment by The-grey-ghost** [comment]
alright possibly the rip I'm using, guess I got to look around and I'm using the basic patch tools for roms to apply English patch

**Comment by agg23** [comment]
Closing for now. Please reopen if you can't fix it

**Comment by The-grey-ghost** [comment]
Reripped and japanese works as well and whatever the IPS patch does I guess makes it bug out.
