### ISSUE TITLE
Super Godzilla display issue

### ISSUE THREAD

**Issue by SigroineyBeaver** [agg23/openfpga-SNES#42]
Snes Super godzilla ntsc rom displays a line at the top of the screen. It looks like the display is shifted down a frame, the bottom of the screen is cut a bit short. 
All current versions of pocket OS and agg23 software as of 9/30/22

**Comment by SegaSnatcher** [comment]
There is a work around for now.   Run a random SNES game (I use Super Battleship) then quit and run Super Godzilla. 

This is the same workaround to fix red line in Genesis core.

**Comment by agg23** [comment]
Possibly related to #18

**Comment by SegaSnatcher** [comment]
> Possibly related to #18

I just confirmed this is another game that uses the 256x249 res.

**Comment by agg23** [comment]
Fantastic, thanks
