### ISSUE TITLE
Can't Get Far East of Eden To Load

### ISSUE THREAD

**Issue by DarkAcid112** [agg23/openfpga-SNES#43]
I've seen people getting this to load, but not having luck on multiple roms. What am I doing wrong?

**Comment by SegaSnatcher** [comment]
The current build doesn't have SPC7110 support yet.   You'd have to use a custom build. 

You can use this as your Far East of Eden core for now, but don't get rid of the main build.  You can switch between the two cores.  

Just unzip this file and add it to your core folder. 

[agg23.SNES-SDD1.zip](https://github.com/agg23/openfpga-SNES/files/9693248/agg23.SNES-SDD1.zip)

**Comment by DarkAcid112** [comment]
Looks like I can get it to run the SPC7110 check program, but getting the NG after every check using the original J rom. When I use the patched English version, I still get a black screen. I guess I’m doing something wrong.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by SegaSnatcher** [comment]
Oh apologies, I forgot that game requires a save file to be placed in the save folder for it to work.   

Just place these in the SNES save folder.  But make sure they follow the same file path as where the rom is placed in your assets.  Also, they need to match the name of the rom as well. 

[Saves.zip](https://github.com/agg23/openfpga-SNES/files/9693309/Saves.zip)

**Comment by DarkAcid112** [comment]
OK, so I have the save files placed in the SNES save folder, and the path is the same where the rom is placed in the assets path. It also has the same name, but I’m still getting the black screen. I chose the SDD1 core as the default as well. Currently on the latest Pocket firmware. Am I missing something?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by SegaSnatcher** [comment]
Try this build.  

[agg23.SNES-SPC7110.zip](https://github.com/agg23/openfpga-SNES/files/9693445/agg23.SNES-SPC7110.zip)

**Comment by DarkAcid112** [comment]
That seems to get me further. It fails on RTC Backup and says reset the system.  Thank you for helping me with this.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by SegaSnatcher** [comment]
That is unfortunate as it works for me without issues.   Not sure what could be the issue.

**Comment by DarkAcid112** [comment]
Thanks anyways. I’ll keep messing around with it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by SegaSnatcher** [comment]
Are you on discord?   If you care to, you can join my server and I can provide everything I have.   

https://discord.gg/jkBQnjTb

**Comment by DarkAcid112** [comment]
Thanks for the help. Issue is now resolved.

**Comment by DarkAcid112** [comment]
Awesome! Thank you. 




Sunday, October 2, 2022 at 1:52 PM -0500 from ***@***.***  ***@***.***>:
