### ISSUE TITLE
Tengai Makyou Zero - RTC fails boot check

### ISSUE THREAD

**Issue by meunierd** [agg23/openfpga-SNES#55]
Firmware: 1.1 Beta 6
Release: 0.4.0
Rom: a1dc8da46fd30dd7fc20359494f35011 (v7.0 of the translation patch)

Screenshot attached, note the `NG`.
![20231113_142039](https://user-images.githubusercontent.com/37849/201538446-40cad618-f360-49fe-bcfb-0c7c53d5a9ee.png)

**Comment by agg23** [comment]
Try deleting the save and following the onscreen instructions again. Make sure to use the reset option in Core Settings.

I experienced this myself, but it was solved by starting over and following the above instructions. If that doesn't work you can also try copying over a known working save.

**Comment by meunierd** [comment]
That did it! Thank you!
