### ISSUE TITLE
[Function request] Is Save States possible?

### ISSUE THREAD

**Issue by MelonGx** [agg23/openfpga-SNES#58]
I plan to play SMW hacks on AP.
Because of the difficulty, I need the save state function.
But it seems that AP’s Save State doesn’t work on OpenFPGA cores.

**Comment by agg23** [comment]
No, save states are not going to happen. It takes a LOT of work for FPGAs, almost akin to making a separate core. If the original core doesn't support it, it's highly unlikely to come to the Pocket.

**Comment by DunhamGitHub** [comment]
I'd love to see this feature.
Tbh, the APocket is useless to me without it.

_...I want to turn it off and have it resume when I turn it back on, I just cannot be bothered to "search a save point" (it's 2023 ffs🤭)_

* I'd contribute an easy 100$ to see this done, probably many would too. Maybe a kickstarter-campaign for this exact feature might be in order
