### ISSUE TITLE
Flashback - The Quest for Identity (US and Europe release) freezes on load

### ISSUE THREAD

**Issue by Juppstein** [agg23/openfpga-SNES#60]
The loading bar goes to 100%, there is a split second of sound and then the screen stays black from that point on. Tried the EU and the US release, both have the same behaviour. I'm using the Pocket firmware 1.1-beta6 and your latest release of the SNES core.

**Comment by agg23** [comment]
Fixed in 0.4.3. Made a small mistake in my ROM header scoring. Sorry about that.
