### ISSUE TITLE
Star Fox EX 1.04.3 blank screen

### ISSUE THREAD

**Issue by DJBabyBuster** [agg23/openfpga-SNES#62]
Just updated the core, and the latest Star Fox EX patch, and I'm getting a blank screen for 1.04.3 with sound.  Version 1.01 works fine.  Just looking to see if you can confirm if 1.04.3 is working, thanks

**Comment by agg23** [comment]
Are you using the patch without FastROM? The FastROM version doesn't work. See https://github.com/MiSTer-devel/SNES_MiSTer/issues/320

**Comment by DJBabyBuster** [comment]
Hi yes using without FastROM, with Star Fox (USA) (Rev 2). I was stumped because as I said patch 1.01 works fine, but the latest 1.04.3 will not load video on my pocket with the the latest snes core 0.4.3

**Comment by DJBabyBuster** [comment]
Okay tried the "SFEX (HARDWARE) (FOR MISTER) 1.04.3.bps" and it's working! Apparently just "SFEX 1.04.3.bps" doesn't work for pocket

**Comment by agg23** [comment]
Glad you figured it out. For some reason some of the patches don't work on MiSTer (and by extension on Pocket).
