### ISSUE TITLE
Video filters? (Super eagle)

### ISSUE THREAD

**Issue by DunhamGitHub** [agg23/openfpga-SNES#69]
Are video filters possible / Why have a 615 ppi screen if I display an 320x240, unfiltered, image on it?

<img width="600" alt="Screenshot 2023-01-28 at 09 45 13" src="https://user-images.githubusercontent.com/6884752/215256544-cda42e39-b9ed-4bbc-97b9-ded4edabec15.png">

<img width="600" alt="Screenshot 2023-01-28 at 09 45 26" src="https://user-images.githubusercontent.com/6884752/215256535-8fa8140c-c69d-4cee-afb9-974780401828.png">

Any?

<img width="257" alt="Screenshot 2023-01-28 at 09 47 52" src="https://user-images.githubusercontent.com/6884752/215256599-20180b93-7b94-4bc5-87b3-ff87f97d4ea6.png">

**Comment by agg23** [comment]
Video filters are a future feature of the Analogue OS. Until those release, few core developers are interested in manually building filters (the only exception I know of is @boogermann, who wrote a basic scanline filter). 

That being said, I doubt many devs are interested in non-linear scaling filters, particularly ones that smooth and distort the image. People using FPGAs are seeking _more_ accuracy over emulators, so messing with the video seems contrary to that goal.
