### ISSUE TITLE
Super Famicom save files

### ISSUE THREAD

**Issue by sax-bit** [agg23/openfpga-SNES#7]
This core recognizes Super Famicom ROMs, but it doesn't seem to recognize any previous Super Famicom save files. It only recognizes my SNES save files for some reason.

Please help!

**Comment by agg23** [comment]
Did you try renaming them? It only looks for files ending in `.sav`

**Comment by OngoGablogian** [comment]
Also the Analogue Pocket organizes save files exactly how your ROMs are organized. If you have a ROM in a folder labeled "SNES Translations" for example, you'd need create a folder in your saves directory with the same name and place the save file in that folder. Otherwise the save file wont be read properly.

**Comment by ifighftdragons** [comment]
> Also the Analogue Pocket organizes save files exactly how your ROMs are organized. If you have a ROM in a folder labeled "SNES Translations" for example, you'd need create a folder in your saves directory with the same name and place the save file in that folder. Otherwise it wont be read properly.

Doesn't the Pocket automatically create these folders for save files?

**Comment by sax-bit** [comment]
Yes, all my files are in .sav format, and yes my saves are labeled AND organized exactly like my ROMs.

I figured it out though. If I don't completely quit the core when I'm ending a game, and then I try to open a game where I have a previous save, it doesn't want to read yhe save at all. It just happened to be a coincidence that this happened when I was trying to play a Super Famicom game instead of an SNES game. 

But yeah, I even noticed in another post that there is occasionally some weird stuff going on with saves with this core that requires you to quit the core completely when switching between games. I imagine my issue is related to that.

**Comment by agg23** [comment]
Closing in favor of #2
