### ISSUE TITLE
Chip32 blob-Error?

### ISSUE THREAD

**Issue by ZidnaZarandur** [agg23/openfpga-SNES#70]
Hello, I choose the manual installation and now I've got this error if I'd like to run a ROM:

Error in framework
Can't find Chip32 blob

What does it mean and how can I fix it? Did I forgot something?
Thank you in advance! =)

**Comment by agg23** [comment]
Did you download the release zip (see instructions on https://github.com/agg23/openfpga-SNES/releases/tag/0.4.3)? Sounds like you downloaded the repo, not the release.

**Comment by ZidnaZarandur** [comment]
Oh my gooood! Thank you SO much!!! My retro-heart is exploding, it works!!
Thank you so much! <3

Am Sa., 4. Feb. 2023 um 20:53 Uhr schrieb Adam Gastineau <
***@***.***>:
