### ISSUE TITLE
FastROM version of Parodius Da! does not load.

### ISSUE THREAD

**Issue by ifighftdragons** [agg23/openfpga-SNES#72]
FastROM version of Parodius Da! does not load. Just stays on a black screen.

Here is the FastROM version, if anyone wants to test for themselves: https://www.romhacking.net/hacks/6432/

**Comment by agg23** [comment]
Does it work on MiSTer? If not, please [open an issue upstream](https://github.com/MiSTer-devel/SNES_MiSTer).

**Comment by ifighftdragons** [comment]
I don't have a MiSTer to check, unfortunately.

**Comment by agg23** [comment]
This hack does not work on MiSTer, and therefore is unrelated to this port. If you have verified this hack works on hardware, you can try opening an issue upstream.
