### ISSUE TITLE
A-Button doesn't work

### ISSUE THREAD

**Issue by codeandcreate** [agg23/openfpga-SNES#74]
The right button "A" doesn't work in all games.
It works in other cores or in the core menu. but not in games.
Is this general problem?!

**Comment by agg23** [comment]
That is really weird. It works correctly for you in other openFPGA cores?

I would mess with the various required files. Delete the core and copy it again, try another SD card, etc. We've found the Pocket is very sensitive to SD and filesystem issues, though I haven't seen cores partially work as of yet.

**Comment by codeandcreate** [comment]
Yeah it works on all other cores, cardrige games (...) on everything else ... i will try to reinstall.

**Comment by agg23** [comment]
> Maybe something has changed in the settings config from 0.4.2 to 0.4.3 ? After i killed the settings json it works again ô.o
Interesting. No, nothing should have changed settings-wise between any of the 0.4 versions.

Did you remap your controls at any point? This sounds like it could be related to that.
