### ISSUE TITLE
favorites 

### ISSUE THREAD

**Issue by gregmariotti** [agg23/openfpga-SNES#76]
I love your core. Thank you for all your hard work. It would be amazing if we could mark games as favorites and that would push them to the top of the list and avoid scrolling through the game list to get back to a certain game. Just a possible enhancement. Thanks so much.

**Comment by agg23** [comment]
Glad you like it. This is an issue with the Analogue Pocket OS, and is not specific to any cores. I do agree it would be a nice feature though

Closing
