### ISSUE TITLE
Megaman X audio issues.

### ISSUE THREAD

**Issue by nrkowalski** [agg23/openfpga-SNES#77]
The audio in Megaman X is not correct. This can be easily reproduced by listening to the intro music specifically during the title screen when the “X” is forming.

**Comment by agg23** [comment]
What is wrong about it specifically? What are you comparing it to?

**Comment by nrkowalski** [comment]
I’m not really sure how to explain it, other than it sounds like it’s missing tones.

you can compare it to this video starting at @1:50

https://youtu.be/f-rJMKeUSIc

or load it up in any emulator or real hardware.
