### ISSUE TITLE
Left and right audio channels are swapped

### ISSUE THREAD

**Issue by naveedster** [agg23/openfpga-SNES#8]
Left and right audio channels are swapped:

https://twitter.com/persianimm0rtal/status/1571019074582491136?s=46&t=KzxF6VltiCglziCTXJnL_Q

First noticed it in legend of zelda:lttp, and star fox 2.

**Comment by SegaSnatcher** [comment]
I was easily able to confirm using the 240p test suite audio test.

**Comment by thedrdodo** [comment]
Can confirm.
