### ISSUE TITLE
[Enhancement] Add option to increase sprite limit 

### ISSUE THREAD

**Issue by wesmckiel** [agg23/openfpga-SNES#94]
Not sure if this a feature that already exists within or would have to be added to the MiSTer core, but I'd love to see an "extra sprites" option like the one present in the agg23 NES core for Pocket.

(If you don't know what I mean: This is a deviation from the original SNES hardware that removes or increases the built-in per-line sprite limit. This reduces sprite "flicker" in many games.)

**Comment by agg23** [comment]
This is something that would have to be added to the upstream MiSTer core. I imagine this feature will not be built due to the complexity of expanding sprite rendering in hardware, and the relatively limited use of such a feature (compared to NES where the sprite limit of 8 is very significant).
