### ISSUE TITLE
An American Tail: Fievel Goes West black screen on launch

### ISSUE THREAD

**Issue by ctafield** [agg23/openfpga-SNES#96]
*An American Tail: Fievel Goes West* doesn't boot. Just gives a black screen on start up.

Doesn't work on the Mister SNES core either, so not sure if it has some unsupported chip?

**Comment by agg23** [comment]
If it doesn't work on MiSTer, it won't work here. You should report the issue upstream to the MiSTer core. It's most likely not an unsupported chip, but some weird edgecase that will be a pain to find.
